## gcloud auth login admin@althenia.fr
## gcloud app deploy --project <PROJECT_ID>

runtime: python312

service: default


handlers:

- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  redirect_http_response_code: 301

- url: /index.html
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  redirect_http_response_code: 301

- url: /(.*\.(js|css|png|jpg|ico|json))$
  static_files: dist/\1
  upload: dist/.*\.(js|css|png|jpg|ico|json)$
  secure: always
  redirect_http_response_code: 301

  # catch all handler to index.html
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  redirect_http_response_code: 301

